name: "Uncrustify"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  uncrustify:
    name: Uncrustify
    runs-on: ubuntu-latest
    env:
      run-uncrust: ${{ false || contains(github.event.head_commit.message, 'Bump version to') || contains(github.event.head_commit.message, 'CI_FORCE_UNCRUST') || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout repository
        if: ${{ env.run-uncrust == 'true' }}
        uses: actions/checkout@v3

      - name: Run style check
        if: ${{ env.run-uncrust == 'true' }}
        uses: coleaeason/actions-uncrustify@v1
        with:
          configPath: 'uncrustify.cfg'
